---
- hosts: node1
  gather_facts: false
  tasks:
  - name: Remove previous deployments
    ansible.builtin.shell: microk8s kubectl delete deployments webgoat -n webgoat
    ignore_errors: yes
  - name: Create a Deployment for webgoat
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: webgoat
          namespace: webgoat
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: webgoat
          template:
            metadata:
              labels:
                app: webgoat
            spec:
              containers:
              - image: "jrolaubi/webgoat"
                imagePullPolicy: IfNotPresent
                name: webgoat
                ports:
                - containerPort: 8080
                - containerPort: 9090
