---
- hosts: node1
  gather_facts: false
  tasks:
  - name: Remove previous deployments
    ansible.builtin.shell: microk8s kubectl delete deployments webgoat -n webgoat && microk8s kubectl delete services webgoat -n webgoat
    ignore_errors: yes
  - name: Pause to complete pod deletion
    pause:
      seconds: 30
  - name: Create a Deployment for webgoat
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: webgoat
          namespace: webgoat
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: webgoat
          template:
            metadata:
              labels:
                app: webgoat
            spec:
              containers:
              - image: "jrolaubi/webgoat-tese"
                imagePullPolicy: IfNotPresent
                name: webgoat
                env:
                - name: TZ
                  value: Europe/London
                ports:
                - containerPort: 8080
                - containerPort: 9090
                - containerPort: 80
                - containerPort: 8888
  - name: Pause to avoid spring startup bugs
    pause:
      seconds: 30
  - name: Create a Service for webgoat
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: webgoat
          namespace: webgoat
        spec:
          selector:
            app: webgoat
          ports:
            - name: webgoat
              protocol: TCP
              port: 8080
              targetPort: 8080
              nodePort: 30680
            - name: webwolf
              protocol: TCP
              port: 9090
              targetPort: 9090
              nodePort: 30690
            - name: webgoat-8888
              protocol: TCP
              port: 80
              targetPort: 8888
              nodePort: 30688
          type: LoadBalancer
          loadBalancerIP: 192.168.128.54
